# Generated by Django 4.2.6 on 2023-12-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('materialType', models.CharField(choices=[('AA5754', 'AA5754'), ('AA6082', 'AA6082'), ('AA7075', 'AA7075')], default='', max_length=50)),
                ('description', models.TextField()),
                ('anisotropic', models.CharField(choices=[('isotropic', 'isotropic'), ('orthotropic', 'orthotropic')], default='', max_length=50)),
                ('uploadImage', models.FileField(default='logos/logo.png', upload_to='logos')),
                ('youngModulus', models.IntegerField()),
            ],
        ),
    ]
