# Generated by Django 4.2.6 on 2023-12-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialCard', '0002_alter_materialcard_youngmodulus'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcard',
            name='possionRatio',
            field=models.IntegerField(default=0),
        ),
    ]
